/**
 * Send email with attachments via Microsoft Graph sendMail
 * Sends from OJ_EMAIL_FROM mailbox to the user-entered address
 */

const TENANT_ID    = process.env.OJ_TENANT_ID!;
const CLIENT_ID    = process.env.OJ_CLIENT_ID!;
const CLIENT_SECRET = process.env.OJ_CLIENT_SECRET!;
const EMAIL_FROM   = process.env.OJ_EMAIL_FROM!;

async function getToken(): Promise<string> {
  const res = await fetch(
    `https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type:    'client_credentials',
        client_id:     CLIENT_ID,
        client_secret: CLIENT_SECRET,
        scope:         'https://graph.microsoft.com/.default',
      }),
    }
  );
  const data = await res.json();
  if (!data.access_token) throw new Error(`Mail auth failed: ${data.error_description}`);
  return data.access_token as string;
}

export interface Attachment {
  name: string;
  contentBase64: string;
}

export async function sendReports(
  toEmail: string,
  repNames: string[],
  dateRange: string,
  attachments: Attachment[]
): Promise<void> {
  const token = await getToken();

  const subject = `Vital Score Card Reports – ${dateRange}`;

  const htmlBody = `
    <div style="font-family:Arial,sans-serif;color:#32373C;">
      <table width="600" cellpadding="0" cellspacing="0" style="margin:0 auto;">
        <tr>
          <td style="background:#DA291C;padding:20px 30px;">
            <h2 style="color:#fff;margin:0;font-size:20px;">Vital Score Card Reports</h2>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 30px;">
            <p>Please find attached the score card report(s) for the following rep(s):</p>
            <ul>
              ${repNames.map((n) => `<li><strong>${n}</strong></li>`).join('')}
            </ul>
            <p><strong>Date range:</strong> ${dateRange}</p>
            <p style="margin-top:24px;color:#888;font-size:12px;">
              Generated by the Vital Score Card Builder.<br/>
              For support, contact <a href="mailto:info@outerjoin.co.za">info@outerjoin.co.za</a>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F2F2F2;padding:12px 30px;text-align:center;font-size:11px;color:#888;">
            OuterJoin – Visualise Efficiency
          </td>
        </tr>
      </table>
    </div>
  `;

  const message = {
    subject,
    body: { contentType: 'HTML', content: htmlBody },
    toRecipients: [{ emailAddress: { address: toEmail } }],
    attachments: attachments.map((a) => ({
      '@odata.type': '#microsoft.graph.fileAttachment',
      name: a.name,
      contentBytes: a.contentBase64,
    })),
  };

  const res = await fetch(
    `https://graph.microsoft.com/v1.0/users/${encodeURIComponent(EMAIL_FROM)}/sendMail`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message, saveToSentItems: false }),
    }
  );

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`sendMail failed (${res.status}): ${text}`);
  }
}
